export const HEADER_TYPE = {
  PHOTO_STORAGE: 'PHOTO_STORAGE',
  BOARD: 'BOARD',
  TRASH_STORAGE: 'TRASH_STORAGE',
};

export const MODAL_TYPE = {
  PHOTO_DETAIL_MODAL: 'PHOTO_DETAIL_MODAL',
  GO_TRASH_MODAL: 'GO_TRASH_MODAL',
  DELETE_MODAL: 'DELETE_MODAL',
  RESTORE_MODAL: 'RESTORE_MODAL',
};

export const MENU_TYPE = {
  NAVIGATION: {
    CATEGORY: 'CATEGORY',
    BOARD: 'BOARD',
  },
};
